name: cargo-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  cargo-test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ stable,windows,macos ]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
#          - build: nightly
#            os: ubuntu-latest
#            rust: nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup component add rustfmt clippy
          rustup update --no-self-update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          rustup -V
          rustc -Vv
          cargo -V
      - name: Build and run tests
        run: cargo test
      - name: Test no default
        run: cargo test --no-default-features